### ISSUE TITLE
discouraged

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/p-timeout#22]
I consider any form of cancelable promise a bad practice. You wanna know why?
cuz promises was not designed with cancelations in mind, and you can't cancel promises such as `fetch()`
That's why AbortController was invented.

if you use a p-timeout or any cancelable library with a Promise.race condition together with fetch then you will still leave the request [hanging](https://stackoverflow.com/a/50101022/1008999)

I know you are using this library in p-event also but really the new way of stop listening to an event is with [AbortSignal + AddEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)

```js
const ctrl = new AbortController()
const { signal } = ctrl
addEventListener('message', fn, { signal })
```
Signal is grate cuz it can allow you to cancel multiple things at once eg when you navigate away from a single page application and want to stop listening to all events on the page, stop all xhr, and so on. They are now supported everywhere, in fs, streams fetch events and so on.

Now i know that signal isn't some form of timer but there are proposals to bring something like ` { signal } = AbortController.timeout(2000)`

**Comment by sindresorhus** [comment]
`AbortController` only exists because the JS standards people could never decide on how to integrate cancellation into Promises, and the web standards, like Fetch, could not wait for it to happen, so they invented `AbortController`. I personally think `AbortController` is an awkward and boilerplaty design. Every single API has to have a `signal` option. It's a leaky abstraction. Proper cancellation support in JS async and promises would have been much better. But this is what we have...

Also, this package was made before `AbortController` was a thing. However, I'm happy to add `AbortController` support: https://github.com/sindresorhus/p-timeout/issues/23

**Comment by jimmywarting** [comment]
Think it would almost be better to leave this as it is and instead add AbortController support directly to p-event instead.

**Comment by sindresorhus** [comment]
> Think it would almost be better to leave this as it is and instead add AbortController support directly to p-event instead.

I don't see how that would help this specific package as it doesn't depend on `p-event`.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-event/issues/40

**Comment by jimmywarting** [comment]
> sindresorhus/p-event#40

is what i wanted to see 👍
